import { Footer, Header } from "@/components";
import "./globals.css";
import { ScrollTopJsx } from "@/components/ScrollTopJsx";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-[#f3f4f6]">
        <Header />
        {children}
        <Footer />
        <ScrollTopJsx />
      </body>
    </html>
  );
}
